upgrade multistream
filecoin-project/go-legs pull request #175
Opened 2023-03-08 12:05 UTC by anjor

In going to v0.4.0 multistream made the ErrNotSupported generic: https://github.com/multiformats/go-multistream/pull/97/files

@brosetti1 has been working on bitswap retrieval for validation bot: https://github.com/data-preservation-programs/ValidationBot/pull/36
and is stuck in dependency issues.

Hopefully this resolves one of his blockers.

2023-03-08 22:06 UTC, willscott commented
can you take a look at the `go mod tidy` / CI checks?

2023-03-08 23:14 UTC, anjor commented
ah looks like this breaks a lot of other stuff, and will require a lot more effort.

2023-04-03 23:56 UTC, gammazero requested changes

2023-04-03 23:56 UTC, gammazero commented on p2p/protocol/head/head.go
> +					}) {
I would recommend moving to https://github.com/ipni/go-libipni/dagsync which is the replacement go-legs. If that is not possible, then change this PR to do as the code there does:
https://github.com/ipni/go-libipni/blob/main/dagsync/p2p/protocol/head/head.go#L80-L95

2023-12-10 15:22 UTC, closed without merging